export const APP_NAME: "ditch-typescript-adopt-jsdoc";
export const DOCUMENT_ROOT: "/" | "/mina/ditch/";
export namespace DATETIME_FORMAT {
    let year: string;
    let month: string;
    let day: string;
    let hour: string;
    let minute: string;
    let second: string;
}
export const COOKIE_NAME_BASE: "ditch";
export const DURATION_MINUTE: 60;
export const DURATION_HOUR: number;
export const DURATION_DAY: number;
export const DURATION_DAYS_30: number;
export const DURATION_DAYS_60: number;
export const DURATION_YEAR: number;
export const DURATION_YEARS_100: number;
export const CACHE_KEY: "ditch-typescript-adopt-jsdoc";
export const CACHE_VERSION: "v1";
export const CACHE_OFFLINE: string;
export const CACHE_NAMES: {};
export const Z_INDEX_FENGSHUI_ER_SHI_SI: 90;
export const Z_INDEX_FENGSHUI_ER_SHI_SI_INFO: 100;
export const Z_INDEX_FENGSHUI_BAGUA: 110;
export const Z_INDEX_FENGSHUI_BAGUA_INFO: 120;
export const Z_INDEX_FENGSHUI_CIRCLE: 130;
export const Z_INDEX_FENGSHUI_NORTH: 140;
export const Z_INDEX_FENGSHUI_JIU_XING_BOXES: 150;
export const Z_INDEX_FENGSHUI_JIU_XING: 160;
export const Z_INDEX_COVER: 400;
export const Z_INDEX_MENU: 500;
export const Z_INDEX_ALERT: 600;
export const BAZI_TYPE_KEYS: string[];
export const GANZHI_TYPE_KEYS: string[];
export const RADIAN_15: number;
export const RADIAN_30: number;
export const RADIAN_45: number;
export const RADIAN_90: number;
